str = "tHiS is a StRiNg"
print(str)
print(str.capitalize())
print(str.casefold())
print(str.center(100))
print(str.count("is"))
print(str.encode())
print(str.endswith(""))
print(str.find("is"))
print(str.isalnum())
print(str.isalpha())
print(str.isdecimal())
print(str.isdigit())
print(str.isidentifier())
print(str.islower())
print(str.isupper())
print(str.isnumeric())
print(str.isspace())
print(str.istitle())
print(str.isprintable())
print("/".join(str))
print(str.ljust(10),"String add")
print(str.lower())
print(str.lstrip())
print(str[1:9])
print(str[:])
print(str.swapcase())
print(str.zfill(50))
print(str.splitlines())
print((str.partition("a")))
print(str.replace("is","is list of"))


numbers = ['one','two','three','four']
numbers.append("five")
print(numbers)
x = numbers.copy()
print(x)
print(numbers.count("two"))

num = ['seven','eight','nine']

numbers.extend(num)
print(numbers)
print(numbers.index("five"))
numbers.insert(5,'six')
print(numbers)
numbers.pop(1)
print(numbers)
numbers.remove("one")
print(numbers)
numbers.reverse()
print(numbers)
numbers.sort()
print(numbers)
numbers.clear()
print(numbers)
